# =======================================#
# -----------DUMBARTON THEME-------------#
# ----------------By: Tyler Butler-------#
#-----------------https://tbutler.org----#
#========================================#

title: Dumbarton Theme 
email: 
description: A minimalistic jekyll theme for academics
baseurl:                                       # the subpath of your site, e.g. /blog
url: "https://dumbarton.netlify.app/"          # the base hostname & protocol for your site, e.g. http://example.com
image:                                         # used to generate site link preview
image_alt:                                     # image description

# =======================================#
# -----------SITE SETTINGS---------------#
#========================================#
author: John Doe 
profile_image: /assets/img/avatar/avatar.png
occupation: 
snippet: 
twitter: tbutler0x90
github: tcbutler320
linkedin: tyler-b-a700a1aa
stackoverflow: 12935605
website: https://tbutler.org
codepen: tcbutler320
email: 
pgp: 
ctftime: 
phonenumber: 

# =======================================#
# -----------THEME SETTINGS--------------#
#===================================
nav-color: light                               # options: light, dark, transparent, primary | Change the color of the navbar
footer-color:
home-highlights-color:
font: Crimson Text                             # Choose any Google API Font,see a list here https://fonts.google.com/?
                                               #        My Top choices are [Bitter,Crimson Text] 
nav-dIcon: "fas fa-caret-down"                 # Change the navbar dropdown (for mobile or small screen sizes) to any fontawesome icon. for a list of icons visit https://fontawesome.com/ 
                                               # =======================================#     # These options include popups, modals, and toasts designed to 
# -------USER INTERACTION SETTINGS-------#     #   make the site more interactive for the user or to highlight
#========================================#     #   certain sections. Powered by BootStrap 4 

home_modal: false
home_toasts: false
home_popup: false

# =======================================#
# -----------BUILD SETTINGS--------------#
#========================================#
theme: 
markdown: kramdown

kramdown:
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-scholar
sass:
  sass_dir: _sass
  style: compressed


include:
  - _posts

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# =======================================#
# -----JEKYLL SCHOLAR SETTINGS-----------#
#========================================#
scholar:
  last_name: Dumbarton
  style: apa
  locale: en
  source: /_bibliography/
  bibliography: papers.bib
  bibliography_template: bib
  replace_strings: true
  join_strings: true
  details_dir: bibliography
  details_layout: bibtex.html
  details_link: 
  query: "@*"

# =======================================#
# ------------CDN SETTINGS---------------#
#-------------Used to generate icons-----#
#========================================#
font_awesome_id: 32a2b2a489                   # Register for free at https://fontawesome.com/ to get your id


# =======================================#    # For more information about these settings, visit https://htmlhead.dev #
# ------------META TAG SETTINGS----------#
#========================================#
themecolor: "#4285f4"                         # Theme Color for Chrome, Firefox OS and Opera -->
google-site-verification:                     #<meta name="google-site-verification" content="verification_token"><!-- Google Search Console -->
yandex-verification:                          #<meta name="yandex-verification" content="verification_token"><!-- Yandex Webmasters -->
msvalidate:                                   # meta name="msvalidate.01" content="verification_token"><!-- Bing Webmaster Center -->
alexaVerifyID:                                # <meta name="alexaVerifyID" content="verification_token"><!-- Alexa Console -->
pinterestdomain_verify:                       #<meta name="p:domain_verify" content="code_from_pinterest"><!-- Pinterest Console-->
norton-safeweb:                               # <meta name="norton-safeweb-site-verification" content="norton_code"><!-- Norton Safe Web -->
detectphone: yes                              # yes or no. Disable automatic detection and formatting of possible phone numbers 
x-dns-prefetch-control: on                    # on or off. Completely opt out of DNS prefetching by setting to "off"
fbappid:                                      # Facebook OpenGraph 